darkube_build_fenjoon-api_fenjoon_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - IMAGE_ADDRESS="registry.hamdocker.ir/fenjoon/fenjoon-api"
  - 'darkube build --push -t $IMAGE_ADDRESS:$CI_COMMIT_SHORT_SHA -t $IMAGE_ADDRESS:$CI_COMMIT_REF_SLUG
    --workdir . --file ./Dockerfile --build-context . '
  stage: build
darkube_deploy_fenjoon-api_fenjoon_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN_FENJOON_API_FENJOON_HAMRAVESH_C13} --app-id
    ${APP_ID_FENJOON_API_FENJOON_HAMRAVESH_C13} --image-tag ${CI_COMMIT_SHORT_SHA}
    --job-id ${CI_JOB_ID}
  stage: deploy